version: '3.5'

services:
  angular-service:
    container_name: ecommerce-angular
    build: ./
    volumes: 
    - './:usr/src/app'
    ports:
      - "4200:80"
    command: >
      bash -c "npm start"